"""Initial schema

Revision ID: e96981882eab
Revises: 
Create Date: 2025-11-18 11:34:56.119872

"""
from alembic import op
import sqlalchemy as sa

from geoalchemy2 import Geometry, Geography

# revision identifiers, used by Alembic.
revision = 'e96981882eab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###